### PR TITLE
Force colors

### PR DESCRIPTION
**Pull request by ghost**
Fix some colours stuff

### CODE REVIEW

**Comment by spencertipping** [comment]
Is there a more portable way to do this? (e.g. using tmux.conf) I found this in the manpage, under the `terminal-overrides` option:

```
The terminal entry value is passed through strunvis(3)
before interpretation.  The default value forcibly cor‐
rects the ‘colors’ entry for terminals which support 88
or 256 colours:

    "*88col*:colors=88,*256col*:colors=256,xterm*:XT"
```

Alternatively, maybe abstract into a `$TMUX_OPTIONS` environment variable.

**Comment by ghost** [comment]
idk, ~/tmux.conf not working for me

**Comment by spencertipping** [comment]
Ok, in that case I'd definitely accept something that used $TMUX_OPTIONS or
similar, rather than hard-coding -2.

**Comment by ghost** [comment]
Well, figure out best way to fix output of [doge](https://github.com/thiderman/doge) program, i`m fine with -2

**Pull request closed without merging**
